import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NotificationProvider} from "@/app/components/providers/NotificationProvider";
import {LoadPageProvider} from "@/app/components/providers/LoadPageProvider";
import {AddPlayListProvider} from "@/app/components/providers/AddPlaylistProvider";
import 'mdui/mdui.css';
import 'mdui';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <NotificationProvider>
          <LoadPageProvider>
              <AddPlayListProvider>
                  {children}
              </AddPlayListProvider>
          </LoadPageProvider>
      </NotificationProvider>
      </body>
    </html>
  );
}
